"""Configuration package for AI Scenario Simulator."""

from config.settings import (
    APP_TITLE,
    APP_SUBTITLE,
    APP_ICON,
    APP_VERSION,
    INTERVIEW_CATEGORIES,
    WORKPLACE_CATEGORIES,
    SCENARIO_CATEGORIES_GROUPED,
    ALL_CATEGORIES,
    DIFFICULTY_LEVELS,
    DEFAULT_DIFFICULTY,
    EXPERIENCE_LEVELS,
    DEFAULT_EXPERIENCE,
    DEFAULT_ROLES,
    DEFAULT_ROLE,
    SCORING_DIMENSIONS,
    SCORING_DIMENSION_LABELS,
    SCORING_DIMENSION_DESCRIPTIONS,
    PROVIDER_GEMINI,
    PROVIDER_GROQ,
    SUPPORTED_PROVIDERS,
)
from config.gemini_config import (
    GEMINI_MODELS,
    DEFAULT_GEMINI_MODEL,
    get_gemini_model_names,
    get_gemini_model_id,
    get_gemini_api_key,
    is_gemini_configured,
)
from config.groq_config import (
    GROQ_MODELS,
    DEFAULT_GROQ_MODEL,
    get_groq_model_names,
    get_groq_model_id,
    get_groq_api_key,
    is_groq_configured,
)

__all__ = [
    "APP_TITLE",
    "APP_SUBTITLE",
    "APP_ICON",
    "APP_VERSION",
    "INTERVIEW_CATEGORIES",
    "WORKPLACE_CATEGORIES",
    "SCENARIO_CATEGORIES_GROUPED",
    "ALL_CATEGORIES",
    "DIFFICULTY_LEVELS",
    "DEFAULT_DIFFICULTY",
    "EXPERIENCE_LEVELS",
    "DEFAULT_EXPERIENCE",
    "DEFAULT_ROLES",
    "DEFAULT_ROLE",
    "SCORING_DIMENSIONS",
    "SCORING_DIMENSION_LABELS",
    "SCORING_DIMENSION_DESCRIPTIONS",
    "PROVIDER_GEMINI",
    "PROVIDER_GROQ",
    "SUPPORTED_PROVIDERS",
    "GEMINI_MODELS",
    "DEFAULT_GEMINI_MODEL",
    "get_gemini_model_names",
    "get_gemini_model_id",
    "get_gemini_api_key",
    "is_gemini_configured",
    "GROQ_MODELS",
    "DEFAULT_GROQ_MODEL",
    "get_groq_model_names",
    "get_groq_model_id",
    "get_groq_api_key",
    "is_groq_configured",
]
